/**
 * Swagger Demo - OpenAPI 3.0
 * This is the description of the API. this is fully customizable, and you can edit it like a standard markdown sheet, and its results will show on the righthand side of the page for documentation purposes
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Todo {
    'id'?: number;
    'description'?: string;
    'done'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "done",
            "baseName": "done",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Todo.attributeTypeMap;
    }

    public constructor() {
    }
}

